[package]
name = "nit-system"
version = "0.1.0"
edition = "2021"
description = "A fast local terminal note system"
repository = "https://github.com/ART3121/NIT-System"
homepage = "https://github.com/ART3121/NIT-System"
readme = "README.md"

[[bin]]
name = "nit"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
crossterm = "0.28"
ratatui = "0.29"
