[package]
name = "nit-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Core domain and storage API for NIT System"

[dependencies]
anyhow.workspace = true
fs2.workspace = true
serde.workspace = true
tempfile.workspace = true
